### ISSUE TITLE
Any plans to support octane / glimmer?

### ISSUE THREAD

**Issue by joegaudet** [LevelbossMike/ember-statecharts#191]
Would love to give this library a spin, any plans to support modern ember?

**Comment by LevelbossMike** [comment]
Hi thanks for this issue!

Yes I definitely plan to support octane and glimmer components. As I'm using this for production apps I'm currently figuring out the best way to do so.

Are you running into issues right now? Are you starting out with a new octane project or are you converting an existing application to octane?

I feel like the `statechart` and `matchesState`-decorators might be useful because they get rid of some boilerplate even with octane. Are there particular things you like to see supported specifically with octane?

**Comment by LevelbossMike** [comment]
@joegaudet 

`ember-statecharts` works just fine with glimmer components right now. As with es6 classes with regular `@ember/component`s you can simply use the `statechart`- and `matchesState`-computeds as decorators.

Here's an example of a button component implemented with ember-statecharts:

Template:

```hbs
<button
  type="button"
  {{on "click" this.submit}}
>
  {{#if this.isBusy}}
    Loading...
  {{else}}
    {{@text}}
  {{/if}}
</button
>
```

Component class:

```js
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { statechart, matchesState } from 'ember-statecharts/computed';
import { task } from 'ember-concurrency';

export default class ButtonComponent extends Component {
  @matchesState('busy')
  isBusy;

  @statechart({
    initial: 'idle',
    states: {
      idle: {
        on: {
          SUBMIT: 'busy'
        }
      },
      busy: {
        onEntry: 'handleSubmit',

        on: {
          SUCCESS: 'success',
          ERROR: 'error'
        }
      },
      success: {
        on: {
          RESET: 'idle'
        }
      },
      error: {
        on: {
          SUBMIT: 'busy'
        }
      }
    }
  }, {
    actions: {
      handleSubmit(context) {
        context.onSubmitTask.perform(context.args.onSubmit || function() {});
      }
    }
  })
  statechart

  @(task(function *(onSubmit) {
    try {
      yield onSubmit();

      this.statechart.send('SUCCESS');
    } catch (error) {
      this.statechart.send('ERROR', { error });
    }

  }))
  onSubmitTask

  @action
  submit() {
    this.statechart.send('SUBMIT')
  }
}

```

Tracked properties might make [actors](https://xstate.js.org/docs/guides/actors.html) and [assign](https://xstate.js.org/docs/guides/context.html#assign-action) more useful in an ember context as well. But this should get you started.

Please let me know if that answers your question. Happy to help!
