### ISSUE TITLE
`.update` function allow diffing old and new contexts

### ISSUE THREAD

**Issue by lougreenwood** [LevelbossMike/ember-statecharts#311]
When using `.update()`, it would be useful to be able to diff the old & new context values to see if any actions should be taken.

For example, if a `context` contains multiple objects, of which some should trigger a machine `restart` and others should not, currently any change to the context object will trigger a restart.

Instead, if we could access the `oldContext` & `newContext` separately, we could diff the specific context objects which should only trigger a `restart` and conditionally trigger the `restart()`.

**Comment by pangratz** [comment]
Heyooo 👋 

With the recent [`onTransition` addition](https://ember-statecharts.com/docs/statecharts#-ontransition) to the API, this should be possible:

```js
@use machine = useMachine(
  /* machine */
)
.onTransition((state) => {
  this._previousContext = state.context;
})
.update(({ send, restart, context }) => {
  if (shouldRestart(this._previousContext, context) {
    restart();
  } else {
    send("HANDLE_UPDATED_CONTEXT_AFTER_CHANGE");
  }
})
```

**Comment by pangratz** [comment]
I'm closing as this should be resolved, feel free to reopen if this is not the case.
