### ISSUE TITLE
Computed properties are not updated on context change

### ISSUE THREAD

**Issue by rreckonerr** [LevelbossMike/ember-statecharts#327]
Hi, thanks for an amazing addon! A great example of `@use` handiness :)

I've noticed that computed properties don't get updated

```hbs
<div>{{this.count}}</div>
```

```js
// ... statechart initialization

// this won't get updated on xstate `assign`
@computed('statechart.state.context.count')
get count() {
    return this.statechart.state.context.count;
}
```

```js
// ... statechart initialization

// this works fine
get count() {
  return this.statechart.state.context.count;
}
```

Is it something obvious that we shouldn't use @computed for retrieving context values or is this a bug?

**Comment by LevelbossMike** [comment]
Hi @rreckonerr and thanks for raising this.

Sorry for getting to this so late - I think we already discussed this in discord though. The `useMachine`-api is based on `tracked`-properties so you can just create `get`ters that will update based on the state.

I'm not entirely sure about the reason for this tbh but using a getter is the way to go with `useMachine` and will work with `assign`.

Closing because this isn't a bug.

**Comment by rreckonerr** [comment]
Thanks, Mike!
It's not a problem to use getter to read the context value, but it gets more complicated when you have a computed property like this:
```
@computed("statechart.state.context.count", "someOtherCount")
get totalCount() {
  return this.statechart.state.context.count + this.someOtherCount;
}
```

It's just confusing that it won't recompute on `context.count` change. Maybe it should be mentioned somewhere in the readme?

Is it possible that context properties are native getters? [dependentKeyCompat](https://api.emberjs.com/ember/release/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat) would solve this issue in that case.

**Comment by LevelbossMike** [comment]
🤔 I wasn't aware that `dependentKeyCompat` existed. Looks like this would be a pretty straight forward change 👏 

Do you want to open a PR for this?

**Comment by rreckonerr** [comment]
@LevelbossMike I'd love to! I already opened somehow similar PR for [another addon](https://github.com/freshbooks/ember-responsive/pull/350/files), but I'm completely lost here 😅
Maybe you can guide me where should I look at?

**Comment by LevelbossMike** [comment]
@rreckonerr The state exposed by the usable is defined [here](https://github.com/LevelbossMike/ember-statecharts/blob/master/addon/usables/use-machine.ts#L134).
