### ISSUE TITLE
Docs might be out of date

### ISSUE THREAD

**Issue by sukima** [LevelbossMike/ember-statecharts#369]
Per the Docs:

> To implement a statechart via ember-statecharts you will make use of the useMachine- usable exported from ember-statecharts. usable support has yet to land in the framework so you will need to make use of ember-usable for now to use the @use-decorator - ember-usable will be installed for you when you install ember-statecharts.

But @NullVoxPopuli says this is no longer true.

**Comment by sukima** [comment]
Also https://ember-statecharts.com/api-docs/modules/usables_use_machine.html#default seems incorrect per the README example.

**Comment by LevelbossMike** [comment]
The docs page is referring to the stable release 0.13.x. The current README is reflecting the master branch, which is released as `0.14.0-beta.x`. https://github.com/LevelbossMike/ember-statecharts/releases/tag/v0.14.0-beta.0

I have yet to deploy the beta docs unfortunately. I'm currently figuring out a way to implement a version switcher on the docs page.

**Comment by LevelbossMike** [comment]
I'm closing this issue as this is something on the radar already - we just need to figure out how to add a versions selector to the docs page. Also adding the documentation label for this.
